eureka:
  client:
    register-with-eureka: false
server:
  port: 8222
spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: students
          uri: http://localhost:8090
          predicates:
            - Path=/api/v1/students/**
        - id: students-swagger
          uri: http://localhost:8090
          predicates:
            - Path=/api/v1/students/swagger-ui/**

        - id: schools
          uri: http://localhost:8070
          predicates:
            - Path=/api/v1/schools/**
        - id: schools-swagger
          uri: http://localhost:8070
          predicates:
            - Path=/api/v1/schools/swagger-ui/**

management:
  tracing:
    sampling:
      probability: 1.0
